name: Ubuntu SSH via ngrok

on:
  workflow_dispatch:

jobs:
  ssh-server:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y openssh-server unzip curl jq

      - name: Configurar SSH
        env:
          PASS01: ${{ secrets.PASS01 }}
        run: |
          sudo mkdir -p /var/run/sshd
          echo "user01:$PASS01" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo /usr/sbin/sshd

      - name: Baixar ngrok
        run: |
          curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
          unzip ngrok.zip

      - name: Autenticar ngrok
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        run: |
          ./ngrok authtoken $NGROK_TOKEN

      - name: Expor SSH com ngrok
        run: |
          ./ngrok tcp 22 --log=stdout &
          sleep 10
          PUBLIC_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Conecte-se ao servidor SSH usando: ssh ubuntu@${PUBLIC_URL#tcp://}"
          # Mantém o job ativo por um período (exemplo: 1 hora)
          timeout 3600 tail -f /dev/null
