name: Ubuntu SSH via ngrok

on:
  workflow_dispatch:

jobs:
  ssh-server:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y openssh-server unzip curl

      - name: Configurar SSH
        run: |
          sudo mkdir -p /var/run/sshd
          echo "ubuntu:senha123" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/Port 22/Port 22/' /etc/ssh/sshd_config
          sudo /usr/sbin/sshd &

      - name: Baixar ngrok
        run: |
          curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
          unzip ngrok.zip

      - name: Autenticar ngrok
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        run: |
          ./ngrok authtoken $NGROK_TOKEN

      - name: Expor SSH com ngrok
        run: |
          ./ngrok tcp 22 &
          sleep 10
          curl -s http://localhost:4040/api/tunnels
