name: SSH via ngrok

on:
  workflow_dispatch:

jobs:
  ssh-server:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y openssh-server unzip curl tar wget

      - name: Criar usuário SSH
        run: |
          sudo useradd -m -s /bin/bash sshuser
          sudo mkdir -p /home/sshuser/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" | sudo tee /home/sshuser/.ssh/authorized_keys
          sudo chown -R sshuser:sshuser /home/sshuser/.ssh
          sudo chmod 700 /home/sshuser/.ssh
          sudo chmod 600 /home/sshuser/.ssh/authorized_keys
          sudo mkdir -p /var/run/sshd
          sudo /usr/sbin/sshd &

      - name: Baixar ngrok
        run: |
          wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar xvzf ngrok-v3-stable-linux-amd64.tgz
      - name: Autenticar ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: ./ngrok authtoken $NGROK_AUTH_TOKEN

      - name: Expor SSH com ngrok
        run: |
          ./ngrok tcp 22 &
          sleep 10
          curl -s http://localhost:4040/api/tunnels | jq '.tunnels[0].public_url'
